module.exports = {
  purge: {
    enabled: true,
    content: ["./src/**/*.{js,jsx,ts,tsx,vue}"],
  },
  theme: {
    extend: {
      colors: {
        primary: "var(--zmp-primary-color)",
        "background-primary": "#F5F5F5",
        gray: "#767A7F",
        divider: "#E9EBED",
        green: "#288F4E",
        background: "#ffffff",
        "background-box": "#FFFDFA",
        skeleton: "rgba(0, 0, 0, 0.1)",
        "primary-color": "#ff0003",
        "text-color": "#fff",
        "text-second-color": "#000000",
        "text-black": "#0D3F67",
        "red-color": "#FE5353",
        "grey-color": "#BFC2C4",
        "grey-second-color": "#3D3D3D",
        "grey-third-color": "#6B7280",
        "green-color": "#9BD929",
        "icon-color": "#27AE60",
        "background-icon": "#F3FFF1",
        "background-gray": "#4C4C4CB2",
        "gray-second": "#E1E3E6",
        "background-box-second": "#D3D3D3",
        "background-gray-second": "#D9D9D9",
      },
    },
  },
  plugins: [require("@tailwindcss/line-clamp")],
};
