enum LOCAL_STORAGE {
  ACCESS_TOKEN = "@access_token",
  REFRESH_TOKEN = "@refresh_token",
}

enum MODE {
  PRODUCTION = "production",
  DEVELOPMENT = "development",
}

enum NAVIGATE_TYPE {
  ZNS = "ZNS",
  SHARE = "SHARE",
  AFFILIATE = "AFFILIATE",
  FLASH_SALE = "FLASH_SALE",
}

const EVENT_ACTION = {
  PRODUCT: {
    CLICK: "PRODUCT_CLICK",
    SEARCH: "PRODUCT_SEARCH",
    LOAD_MORE: "LOAD_MORE_PRODUCT",
    ADD_TO_CART: "ADD_TO_CART",
    CLICK_BUY_NOW: "CLICK_BUY_NOW",
  },
  CATEGORY_PRODUCT: {
    CLICK: "CATEGORY_PRODUCT_CLICK",
    SEARCH: "CATEGORY_PRODUCT_SEARCH",
    LOAD_MORE: "LOAD_MORE_CATEGORY_PRODUCT",
  },
  FLASH_SALE: {
    CLICK: "FLASH_SALE_CLICK",
    LOAD_MORE: "LOAD_MORE_FLASH_SALE",
  },
  SALE_FOR_NEW_CUSTOMER: {
    CLICK: "SALE_FOR_NEW_CUSTOMER_CLICK",
  },
  SUBSCRIPTION: {
    CLICK: "SUBSCRIPTION_CLICK",
    LOAD_MORE: "LOAD_MORE_SUBSCRIPTION",
  },
  BANNER: {
    CLICK: "BANNER_CLICK",
  },
};

export { LOCAL_STORAGE, MODE, NAVIGATE_TYPE, EVENT_ACTION };
